spring:
  application:
    name: todolist
  datasource:
    url: jdbc:mysql://localhost:3306/todolist_be
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        jdbc:
          time_zone: Asia/Seoul
    show-sql: true
  config:
    import: classpath:application-secret.yml